name: Build Amazon EFS Utils

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git binutils rustc cargo pkg-config libssl-dev

      - name: Build amazon-efs-utils
        run: |
          ./build-deb.sh
      
      - name: Upload built .deb package
        uses: actions/upload-artifact@v2
        with:
          name: amazon-efs-utils
          path: ./build/amazon-efs-utils*.deb
